/*
 * dsdvmsgmgr.h
 *
 *  Created on: 2011-11-11
 *      Author: lastland
 */

#ifndef DSDVMSGMGR_H_
#define DSDVMSGMGR_H_

/*
 * This function would translate the information of current
 * node into a string.
 * The node is given as the first parameter and the result
 * would be saved in the second one.
 * The string can be translated back to a node via msg_to_node.
 */
void node_to_msg(NODE* node, char* msg);

/*
 * This function would translate a string into a NODE.
 * The string is given as the first parameter and the result
 * would be saved in the second one.
 * This can only translate string generated by node_to_msg
 * function or others in the same pattern.
 */
void msg_to_node(char* msg, NODE* node);

#endif /* DSDVMSGMGR_H_ */
